version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # IMPORTANT: Update the image tag to the latest version before deploying
    # This is needed due to the way portainer handles image updates
    image: barcode-api:v0.0.1
    container_name: barcode-api
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PORT:-8000}:8000

    environment:
      # Resolved automatically by docker-compose from .env file and shell environment
      - POSTGRES_SERVER=${POSTGRES_SERVER:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:?err}
      - OIDC_BASE_AUTHORIZATION_SERVER_URI=${OIDC_BASE_AUTHORIZATION_SERVER_URI:?err}
      - OIDC_ISSUER=${OIDC_ISSUER:?err}
      - OIDC_SIGNATURE_CACHE_TTL=${OIDC_SIGNATURE_CACHE_TTL:?err}
      # Image specific environment variables
      - BROWSER_PATH=/usr/bin/chromium
