"""Redo migrations

Revision ID: 10570f725f26
Revises:
Create Date: 2023-05-22 00:30:36.417395

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10570f725f26"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ImageData",
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "ScrapeData",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("barcode", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ScrapeData_barcode"), "ScrapeData", ["barcode"], unique=False)
    op.create_table(
        "ShoppingList",
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("list_title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ShoppingList_owner_user_id"), "ShoppingList", ["owner_user_id"], unique=False)
    op.create_table(
        "Product",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("barcode", sa.String(length=255), nullable=False),
        sa.Column("thumbnail_uuid", sa.UUID(), nullable=True),
        sa.Column("barcode_image_uuid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["barcode_image_uuid"],
            ["ImageData.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thumbnail_uuid"],
            ["ImageData.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Product_barcode"), "Product", ["barcode"], unique=True)
    op.create_table(
        "ShoppingListItem",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["ShoppingList.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["Product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ShoppingListItem")
    op.drop_index(op.f("ix_Product_barcode"), table_name="Product")
    op.drop_table("Product")
    op.drop_index(op.f("ix_ShoppingList_owner_user_id"), table_name="ShoppingList")
    op.drop_table("ShoppingList")
    op.drop_index(op.f("ix_ScrapeData_barcode"), table_name="ScrapeData")
    op.drop_table("ScrapeData")
    op.drop_table("ImageData")
    # ### end Alembic commands ###
