"""Added scraping model

Revision ID: 73e3447451b0
Revises:
Create Date: 2023-05-14 01:22:57.643333

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73e3447451b0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ScrapeResult",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("barcode", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ScrapeResult_barcode"), "ScrapeResult", ["barcode"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ScrapeResult_barcode"), table_name="ScrapeResult")
    op.drop_table("ScrapeResult")
    # ### end Alembic commands ###
