"""Added models from ERD diagram

Revision ID: b1075f4d93a0
Revises: da6a18c2aaeb
Create Date: 2023-05-20 23:07:35.347922

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1075f4d93a0"
down_revision = "da6a18c2aaeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ImageData",
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "ScrapeData",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("barcode", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ScrapeData_barcode"), "ScrapeData", ["barcode"], unique=False)
    op.create_table(
        "ShoppingList",
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("list_title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ShoppingList_owner_user_id"), "ShoppingList", ["owner_user_id"], unique=False)
    op.create_table(
        "Product",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("decription", sa.TEXT(), nullable=True),
        sa.Column("manufacturer", sa.String(length=255), nullable=True),
        sa.Column("barcode", sa.String(length=255), nullable=False),
        sa.Column("thumbnail_uuid", sa.UUID(), nullable=True),
        sa.Column("barcode_image_uuid", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["barcode_image_uuid"],
            ["ImageData.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thumbnail_uuid"],
            ["ImageData.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Product_barcode"), "Product", ["barcode"], unique=True)
    op.create_table(
        "ShoppingListItem",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["ShoppingList.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["Product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_ScrapeResult_barcode", table_name="ScrapeResult")
    op.drop_table("ScrapeResult")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ScrapeResult",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"ScrapeResult_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("barcode", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("html", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("scrape_strategy", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="ScrapeResult_pkey"),
    )
    op.create_index("ix_ScrapeResult_barcode", "ScrapeResult", ["barcode"], unique=False)
    op.drop_table("ShoppingListItem")
    op.drop_index(op.f("ix_Product_barcode"), table_name="Product")
    op.drop_table("Product")
    op.drop_index(op.f("ix_ShoppingList_owner_user_id"), table_name="ShoppingList")
    op.drop_table("ShoppingList")
    op.drop_index(op.f("ix_ScrapeData_barcode"), table_name="ScrapeData")
    op.drop_table("ScrapeData")
    op.drop_table("ImageData")
    # ### end Alembic commands ###
