"""Fixed typo in product model

Revision ID: bec9c8df1564
Revises: b1075f4d93a0
Create Date: 2023-05-21 00:41:32.221335

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bec9c8df1564"
down_revision = "b1075f4d93a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "ImageData", ["id"])
    op.add_column("Product", sa.Column("description", sa.TEXT(), nullable=True))
    op.drop_column("Product", "decription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Product", sa.Column("decription", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("Product", "description")
    op.drop_constraint(None, "ImageData", type_="unique")
    # ### end Alembic commands ###
