"""unique uuid for thumbnails

Revision ID: c59b66bd41d5
Revises: 87e76339ad5d
Create Date: 2023-06-07 21:01:25.438871

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c59b66bd41d5"
down_revision = "87e76339ad5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("Product_barcode_image_uuid_unique", "Product", ["barcode_image_uuid"])
    op.create_unique_constraint("Product_thumbnail_uuid_unique", "Product", ["thumbnail_uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Product_barcode_image_uuid_unique", "Product", type_="unique")
    op.drop_constraint("Product_thumbnail_uuid_unique", "Product", type_="unique")
    # ### end Alembic commands ###
