"""Added scraping name column

Revision ID: da6a18c2aaeb
Revises: 73e3447451b0
Create Date: 2023-05-14 03:25:25.430943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "da6a18c2aaeb"
down_revision = "73e3447451b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ScrapeResult", sa.Column("scrape_strategy", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ScrapeResult", "scrape_strategy")
    # ### end Alembic commands ###
