"""Fixed typo in product model_2

Revision ID: daec27183618
Revises: bec9c8df1564
Create Date: 2023-05-21 03:03:54.932664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "daec27183618"
down_revision = "bec9c8df1564"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
